version: '3'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .docker
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://myuser:mypassword@db:3306/mydb'

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html:ro
    depends_on:
      - web

volumes:
  db-data: