version: '3.5'

volumes:
  db-data:

services:
  nginx-php-service:
    container_name: nginx-php-service
    image: nginx:1.24
    restart: no
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/
      - ./.docker/config/nginx/:/etc/nginx/conf.d/
    networks:
      - net-php-service

  php-php-service:
    build:
      context: ./.docker/
    container_name: php-php-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    environment:
      - php_extensions=-mysqli
    networks:
      - net-php-service

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 'risenovsky'
      MYSQL_DATABASE: 'gothic'
      MYSQL_USER: 'dobr'
      MYSQL_PASSWORD: 'risenovsky'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./data/gothic:/docker-entrypoint-initdb.d
    networks:
      - net-php-service

  web:
    build: .docker
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://dobr:tonysold@db:3306/gothic'
    networks:
      - net-php-service

networks:
  net-php-service: