name: gothic

services:
  # PHP FPM Service
  php:
    container_name: php_gothic
    build:
      context: .
    volumes:
      - '../:/var/www/html'
      - './php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    container_name: nginx_gothic
    image: nginx:latest
    ports:
      - 8081:80
    links:
      - 'php'
    volumes:
      - '../:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php


  # MariaDB Service
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'risenovsky'
      MYSQL_DATABASE: 'gothic'
      MYSQL_USER: 'dobr'
      MYSQL_PASSWORD: 'risenovsky'
      MYSQL_HOST: 'localhost'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./data/gothic:/docker-entrypoint-initdb.d

# Volumes
volumes:
  mysqldata:
